---
title: "Berkenalan dengan Spiral Dynamic Optimization Algorithm"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/ikanx101 BLOG/_posts/matematika ITB/analisa numerik lanjut/meta spiral")
```

## Pendahuluan

Di blog saya ini, saya seringkali membahas bagaimana matematika bisa digunakan untuk memodelkan masalah _real_ terkait dengan [optimisasi](https://ikanx101.com/tags/#optimization-story), yakni pencarian suatu nilai solusi yang bisa memaksimalkan atau meminimalkan suatu kondisi. Namun jika kalian menyadari, hal yang saya bahas masih terbatas pada masalah _mixed integer linear programming_ saja.

Sejatinya masalah optimisasi yang ada pada dunia matematika sangatlah luas. Mulai dari bentuk _objective function_ yang non linear sampai masalah yang tidak memiliki _constraints_ sama sekali. 

Masalah optimisasi ini lebih panjang sejarahnya dibandingkan optimisasi yang berkaitan dengan _operational research_, yakni sejak zaman kalkulus dikembangkan (masalah pencarian titik maksimal atau minimal). 

Hal yang menarik bagi saya adalah, ternyata metode pencarian titik maksimum atau minimum ini bisa dikembangkan untuk mencari solusi dari berbagai tipe permasalahan seperti pencarian akar persamaan dengan hanya memodifikasi bentuk _objective function_ asalnya.

Untuk menyelesaikan suatu permasalahan optimisasi, setidaknya ada dua pendekatan yang bisa kita lakukan. Yakni:

1. Metode eksak,
1. Metode _meta heuristic_.

Permasalahannya tidak semua dari kita memahami bagaimana cara melakukan metode eksak karena membutuhkan pengetahuan matematis yang ekstra. Selain itu beberapa permasalahan kadang tidak memiliki solusi secara eksak.

Oleh karena itu banyak orang berlomba-lomba untuk mengembangkan metode numerik lain yang lebih mudah dikerjakan dan secara intuitif bisa digunakan untuk menyelesaikan permasalahan tersebut. Metode-metode ini terinspirasi dari kejadian alam seperti: pergerakan kawanan hewan, pergerakan benda angkasa, persilangan gen, dan lainnya. Metode ini dikenal dengan nama _meta heuristic_.


## _Spiral Dynamic Optimization Algorithm_

Salah satu algoritma _meta heuristic_ yang saya pelajari selama kuliah di semester kemarin adalah _spiral dynamic optimization algorithm_ yang pertama kali diperkenalkan dua ilmuwan asal Jepang pada 2011. Kemudian dua orang matematikawan ITB menyempurnakannya dengan menambahkan algoritma _SOBOL sequence_ agar pencarian solusi bisa lebih sempurna.

SDOA ini bisa digunakan untuk berbagai macam tipe permasalahan.

Saya ingin sekali menulisnya di blog ini, tapi sayangnya terbentur pada notasi-notasi matematika yang terbatas di _github pages_. Oleh karena itu saya telah menulis __empat tulisan__ spesial terkait SDOA.

## Tulisan I

Pada tulisan pertama ini, saya jelaskan bagaimana prinsip utama dari SDOA dan bagaimana cara kerjanya beserta skrip __R__ yang dibuat sendiri untuk itu.

Pada tulisan ini juga saya memberatkan penggunaan SDOA untuk masalah pencarian akar persamaan dan akar sistem persamaan. Baik untuk variabel kontinu atau diskrit.

Silakan menuju [_link_ ini](https://rpubs.com/QRA_NFI/spiral).

## Tulisan II

Pada tulisan ini saya menggunakan SDOA untuk menyelesaikan masalah _mixed integer programming_. Baik untuk masalah linear atau non linear. 

Ini merupakan kabar gembira karena `library(ompr)` yang selama ini saya gunakan untuk menyelesaikan masalah optimisasi tidak bisa memproses _objective function_ berbentuk non linear.

Silakan menuju [_link_ ini](https://rpubs.com/QRA_NFI/SOA_2).

## Tulisan III

Pada tulisan ini saya menggunakan SDOA untuk mencari model _machine learning_ terbaik melalui _feature selection_. Walaupun saya menggunakan model regresi tapi prinsipnya sama dengan model _machine learning_ klasifikasi.

Silakan menuju [_link_ ini](https://rpubs.com/QRA_NFI/SOA_3).

## Tulisan IV

Pada tulisan ini saya menggunakan SDOA bersama dengan algoritma _travelling salesperson problem_ (TSP) untuk melakukan pengelompokkan (_clustering_) dari data yang berisi variabel-variabel _binary_.

Silakan menuju [_link_ ini](https://rpubs.com/QRA_NFI/SOA_4).


# Penutup

Penggunaan SDOA ini sangat luas sekali dan cenderung mudah dilakukan. Tergantung dari kreativitas kita dalam menentukan _objective function_ dari setiap permasalahan tersebut.

Batasan permasalahan yang saya temui hanya pada jumlah variabel keputusan yang tidak bisa lebih dari 200 variabel. Karena matriks rotasi dengan ukuran lebih dari $200 \times 200$ akan berat secara komputasi.