---
title: "Membuat Program Generator Soal Matematika untuk Anak SD"
output: github_document
---

```{r,include=FALSE}
rm(list=ls())
```

Saya masih ingat betul di bulan Maret 2020 saya mulai 100% WFH dan si sulung 100% SFH. Seketika saya dan istri mau tak mau harus mengambil alih peran gurunya di sekolah untuk mengajarkan semua materi mata pelajaran yang ada di buku.

Salah satu materi di mata pelajaran matematika adalah __berhitung__, yakni: penjumlahan, pengurangan, perkalian, dan pembagian. Seiring dengan penambahan waktu, materi si sulung berkembang menjadi pengurutan bilangan, operasi di pecahan, dan faktorisasi bilangan prima.

Bagi saya, mengajar dan memberikan evaluasi adalah dua hal yang berbeda. Mengajar adalah proses _transfer knowledge_ sehingga agak sulit untuk dibuat menjadi otomatis. Berbeda dengan proses __memberikan evaluasi__. Kita bisa membuatnya menjadi otomatis.

Atas dasar itu, saya mencoba membuat suatu program sederhana di __R__ yang berguna untuk membuat soal berhitung secara otomatis. Beberapa bulan yang lalu, saya sempat menuliskan bagaimana membuat soal di __R__ di tulisan [berikut](https://ikanx101.com/blog/soal-berhitung/). Sekarang saya tinggal mengembangkannya menjadi suatu program di mana _user_ mendapatkan soal, menjawabnya, dan menerima _feedback_ atas jawaban tersebut.

Proses membuat programnya tidak serumit yang dibayangkan _kok_. Justru relatif simpel dan mudah.

Jika rekan-rekan sempat membaca tulisan saya terkait [_computational thinking_](https://ikanx101.com/blog/comp-think/), saya sempat _mention_ bagaimana proses dekomposisi dan _modular_ akan sangat berguna saat kita hendak membuat suatu model komputasi (dalam hal ini berupa program).

---

## Ide Dasar

Ide dasar dari program ini adalah:

1. Men-_generate_ dua angka secara acak untuk kemudian dijadikan soal penjumlahan, pengurangan, pembagian, dan perkalian. 
1. Untuk soal pengurutan, di-_generate_ 4-5 bilangan secara acak di suatu _range_ bilangan tertentu. 
1. Untuk faktorisasi bilangan prima, kita bisa menggunakan algoritma yang pernah saya tulis di [tulisan ini](https://ikanx101.com/blog/algo-faktor/).

Masing-masing saya buat _functions_ kecil-kecil. Setelah itu, semua _functions_ tersebut akan digabung ke dalam suatu _function_ yang berguna sebagai _user interface_.

Tingkat kesulitan soal juga bisa disesuaikan sesuai dengan kelas anak. Kita bisa mengatur seberapa "besar" bilangan yang _randomly generated_.

---

## Contoh _Function_

Untuk membuat keseluruhan program, kita akan mulai dari beberapa _functions_ kecil seperti _function_ yang berfungsi untuk _generator_ soal. Sebagai contoh saya akan menjelaskan bagaimana cara kerja _function_ penjumlahan.

### Penjumlahan

Intinya adalah generate soal, cek jawaban _user_, dan catat waktu yang dibutuhkan _user_ untuk menjawab soal tersebut.

Berikut adalah _function_ yang saya buat:

```
penjumlahan = function(){
  bilangan = sample(50:5000,2,replace = F)
  kunci = sum(bilangan)
  
  soal = paste(bilangan,collapse = " + ")
  soal = paste0(soal," = ")
  
  start = Sys.time()
  jawab = readline(prompt = soal)
  jawab = as.numeric(jawab)
  end = Sys.time()
  waktu = end-start
  
  cek = jawab == kunci
  if(cek == T){cat("Kamu Benar!\n\n")}
  else {cat("Kamu Salah... Jawaban yang benar adalah: ",kunci,"\n\n")}
  
  output = list(waktu,cek)
  return(output)
}
```
