---
title: "Review Kuliah Semester I di Magister Sains Komputasi ITB"
output:
  github_document:
    pandoc_args: --webtex
---

```{r setup, include=FALSE}
rm(list = ls())
```

Tidak terasa perkuliahan di semester I ini sudah _officially_ berakhir saat kami semua mengirimkan tugas kuliah paling akhir di tanggal 31 Desember 2021 malam kemarin. Ternyata memang enam bulan itu singkat _yah_.

Pada saat awal-awal kuliah, banyak rekan yang bertanya kepada saya:

> _Memangnya kuliah di sains komputasi itu belajar apa aja sih?_

Dengan simpelnya saya menjawab:

> _Kamu tau artificial intelligence kan? Nah, belajar bikin itu._

Jawaban yang setengah ngasal, sebagian cari cepetnya, dan sisanya ada benarnya. _hehe_.

Jadi inti dari perkuliahan di semester I ini adalah mengenalkan apa itu sains komputasi. Sejatinya sains komputasi berkutat pada penyelesaian masalah-masalah yang ada di sains secara komputasi. Berhubung sains itu luas, maka aplikasinya bisa dibilang tak terbatas. _Applicable_ sekali untuk berbagai bidang industri.

Semua mata kuliah wajib dan pilihan ternyata saling terhubung dan tidak bisa dipisahkan sama sekali. Dua hal yang menjadi benang merahnya adalah _coding / algorithm_ dan _numerical methods_. Oke, sekarang saya coba _review_ satu-persatu _yah_:

## Analisa Numerik Lanjut

Sesuai dengan namanya, mata kuliah ini adalah kelanjutan dari mata kuliah `metode numerik` yang pernah saya ikuti pada saat S1 dulu. Lantas apa perbedaannya? Jika dulu saya belajar bagaimana cara membuat algoritma untuk menyelesaikan masalah matematis secara numerik. Kini lebih jauh daripada sekedar membuat. Kami diajarkan dan diberikan kesempatan untuk mencari tahu hingga memahami prinsip-prinsip dibalik metode numerik tersebut. 

Siapa sangka ternyata prinsip dibalik metode-metode numerik tersebut adalah __aljabar__. Konvergensi dari suatu iterasi ternyata dapat dilihat dari sifat-sifat yang ada di matriks iterasinya.

> _Sungguh menarik..._

Saya sangat menyarankan agar beberapa materi yang ada pada mata kuliah ini bisa diketahui oleh para mahasiswa S1 yang sedang belajar __Aljabar Linear__. Ini adalah salah satu aplikasi _real_ dari _Aljabar Linear_.

_Oh iya_, ada satu macam algoritma _meta heuristic_ baru yang pertama kali saya pelajari di sini.

## Pemrograman dalam Sains

## Jaringan dan Komputasi Parallel

## Algoritma dan Rancangan Perangkat Lunak

