---
title: "Review Menggunakan ngrok untuk Forward RStudio Server ke Internet" 
output: github_document
---

Jika rekan-rekan mengikuti tulisan saya d blog ini, saya telah menceritakan bagaimana saya meng-_install_ [R Studio Server ke dalam laptop Ubuntu OS](https://ikanx101.com/blog/rstudio-server/). Awalnya saya melakukan hal tersebut agar saya memiliki satu _dedicated server_ untuk R Studio yang bisa saya gunakan di intranet rumah. Mengingat rumah saya `waktu itu` sangat luas. _hehehe_. 

Seiring dengan meredanya pandemi, kebutuhan akan R Studio yang bisa digunakan di mana saja menggunakan perangkat yang lebih ringkas pun meningkat. 

Di blog ini juga, saya telah bercerita:

- Bagaimana menggunakan R Studio Cloud (_web based_), 
- Bagaimana meng-_install_ [R Studio Server di Google Colab](https://ikanx101.com/blog/r-server-colab/), 
- Bagaimana meng-_install_ [R Studio Server di _virtual machine_ Google Cloud](https://ikanx101.com/blog/google-rstudio/). 

Seakan masih ingin mencari alternatif lain yang gratis dan _reliable_, saya sekarang ingin menginformasikan sekaligus me-_review_ cara penggunaan suatu _software_ bernama __ngrok__ agar R Studio Server dalam laptop Ubuntu OS saya bisa digunakan dari luar intranet rumah.

Fungsi utama dari __ngrok__ adalah melakukan IP _forwarding_ dari intranet ke luar. Sehingga semua _server_ atau aplikasi dalam _local_ intranet kita bisa akses dari luar tanpa harus _setting_ DNS dan IP publik. Cara penggunaannya juga sangat mudah.

## Instalasi __ngrok__

Untuk melakukan instalasinya di Ubuntu, cukup _run_ perintah berikut pada _terminal_:

```
sudo snap install ngrok
```

maka proses instalasi akan segera dijalankan. 

Setelah itu navigasikan _browser_ ke situs [__ngrok__](https://ngrok.com/). Kita hanya perlu mendaftar (gratis) untuk mendapatkan `authtoken`. Kita bisa gunakan akun `github` untuk memudahkan proses _sign up_. 

Prosesnya juga mudah, cukup ikuti perintah dari situsnya tersebut. Jika berhasil, kita hanya perlu melakukan _running_ perintah berikut ini di _terminal_:

```
ngrok config add-authtoken YOUR_TOKEN_HERE
```

## _Forwarding_ R Studio Server

Secara _default_ R Studio Server berjalan di port 8787. Kita bisa mengaksesnya langsung via _browser_ dengan alamat `localhost:8787`. Oleh karena itu agar _localhost_ di _port_ 8787 bisa diakses internet luas, kita perlu mem-_forward_-nya.

Kita cukup mengetikkan perintah berikut ini di _terminal_:

```
ngrok http localhost:8787

```

Setelah itu, kita tinggal tunggu prosesnya. Tidak lama, dalam waktu kurang dari 10 detik, __ngrok__ akan memberikan alamat situs hasil _forwarding_ tersebut. 

Proses telah selesai. Untuk mencobanya, kita tinggal mengakses alamat situs tersebut menggunakan _gadget_ lainnya. 

Jika sudah selesai, kita tinggal mematikan layanan __ngrok__ saja.

---

Bagaimana? Mudah kan?