---
title: "DIY Robotic Process Automation with R"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(nomnoml)
```

Catatan: _posting_ ini mengandung konten _ngegas_.

Beberapa bulan lalu, tiba-tiba istilah _Robotic Process Automation_ (disingkat __RPA__) menjadi buah bibir di kantor saya. Usut punya usut ternyata baru saja ada _training_ dari suatu _vendor_ terkait pembuatan dan penerapan __RPA__ di kantor.

Tujuannya sangat mulia, yakni agar pekerjaan repetitif menjadi otomatis dan digantikan dengan robot (algoritma).

Setelah kepo tanya sana-sini, ternyata _tools_ yang digunakan adalah _software_ bernama __UIPath__. Bukan _software_ gratisan tapi bisa aja digunakan tanpa membayar. Tentu dengan keterbatasan tertentu _yah_.

Sampai beberapa saat lalu, saya kembali berbincang dengan beberapa rekan terkait _follow up_ dari _training_ tersebut, ternyata belum ada satu _project_-pun terkait __RPA__ yang sudah jalan.

> Mmh, kenapa yah? Jangan-jangan kasusnya sama dengan yang saya [alami dulu](https://ikanx101.github.io/blog/blog-promo-hemat-id/). Hahaha.

____

## Kenapa pakai _UIPath_?

Sempat saya bertanya hal tersebut kepada para peserta training, mereka juga tahunya itu yang diajarkan. Konon katanya software tersebut bisa berinteraksi dengan berbagai macam software lain di komputer.

> Wah keren nih pikir saya.

Tapi setelah berpikir kembali, kayaknya 95% kerjaan orang kantor banyak di Excel deh. _So_