---
title: "Akhirnya Saya Kuliah Lagi...!"
output: 
  github_document:
    pandoc_args: --webtex
---

```{r setup, include=FALSE}
setwd("~/ikanx101 BLOG/_posts/matematika ITB/kuliah lagi")
knitr::opts_chunk$set(echo = TRUE)
```

Sejak lulus kuliah tahun 2008 lalu dari Matematika ITB, ada terbersit keinginan saya untuk kembali kuliah di jenjang magister. Tapi karena satu dan lain hal, saya tidak mengambil jalan tersebut dan lebih fokus membangun karir. Hingga pada bulan puasa lalu, saya dijodohkan Allah SWT untuk kembali bertemu dengan banyak orang baik yang membantu saya membukakan jalan untuk meraih asa yang dulu sempat ada.

Sebenarnya pada 2020 lalu, saya hendak mengikuti ujian masuk S2 di Magister Teknik Industri Universitas Indonesia. _Qodarullah_ saat tes bertepatan dengan awal mula pandemi. Akhirnya setelah berdiskusi dengan istri, saya membatalkan rencana tersebut.

Pada tahun ini, bermodalkan rekomendasi dari beberapa dosen saya di Matematika ITB, saya mencoba mendaftar kuliah di jurusan __Sains Komputasi__ di bawah Program Studi Matematika ITB melalui jalur ___Magister by Research___.

---

> ___Sains Komputasi itu apa sih?___

Pertama kali saya mendengar istilah _computational science_ adalah pada saat saya mengikuti _event_ [Indonesia AI Summit](https://passingthroughresearcher.wordpress.com/2019/08/22/summary-event-indonesian-artificial-intelligence-summit-2019-day-1-keynote-speaker-1/). Salah seorang _keynote speaker_ mengatakan bahwa _buzzword_ seperti ___Artificial Intelligence___ sejatinya adalah ___Computational Science___.

Meminjam definisi yang ada di Wikipedia:

___Computational science, also known as scientific computing or scientific computation, is a rapidly growing field that uses advanced computing capabilities to understand and solve complex problems.___

> ___Kenapa sih pilih jurusan itu?___

Jujur, semenjak _buzzwords_ seperti ___big data___ melesat beberapa tahun silam, _buzzwords_ lain seperti ___artificial intelligence___ juga merajai _top of mind_ para _leaders_ di berbagai organisasi (baca: perusahaan). Banyak konsultan yang hadir menawarkan layanan ini, baik dari dalam negeri hingga dari luar negeri. Namun apakah semua konsultan tersebut benar-benar _capable_ dan _reliable_? 

Berdasarkan pengalaman pribadi saya, jawabannya: __tidak__. Tapi perlu diingat lagi bahwa bisa jadi pengalaman saya berbeda dengan pengalaman Anda ya.

Oleh karena itu, besar keinginan saya untuk belajar dari orang-orang yang benar-benar ahlinya (akademisi). Bagi saya yang selama ini berkutat di dunia praktisi, belajar dari akademisi sangat membuka wawasan dan biasanya ilmu "baru" tersebut selalu bisa diaplikasikan di dunia kerja saya.

> ___Persiapannya apa saja?___

Secara teknis, untuk kuliahnya sendiri kita diharapkan sudah memiliki dasar pemrograman dan _coding skill_ yang cukup. Mengenai bahasanya sendiri, boleh _Python_ atau __R__ atau apapun itu.

Namun setelah saya berdiskusi dengan salah satu dosennya, _Python_ lebih dipilih. Tapi tenang saja, beralih dari satu bahasa ke bahasa lain harusnya tidak terlalu sulit jika kita sudah punya kemampuan _programming_ yang cukup. 

Mengenai tes masuknya sendiri, ada beberapa yang harus dipersiapkan:

1. Tes wajib:
    - Matematika, meliputi: kalkulus, aljabar linear elementer, dan metode numerik.
    - Pemrograman, meliputi: _design thinking_ dan _problem solving_ saat menuliskan algoritma tertentu.
1. Tes wajib pilihan, peserta tes diharuskan memilih 2 dari beberapa subjek di bawah ini:
    - Fisika, meliputi fisika klasik (hukum newton) dan penurunan rumusnya.
    - Data sains, meliputi _problem solving_ saat mendapatkan masalah pada data.
    - Kimia.
    - _Bioscience_.
    - _Science material_.
    
> ___Tes masuknya apa saja?___

Saat saya mengetahui materi tes masuknya adalah _pure_ matematika (bukan tes potensi akademik biasa), saya harus membuka-buka kembali buku kalkulus, aljabar linear elementer, dan metode numerik dalam waktu 2 minggu. [Tulisan terakhir saya kemarin](https://ikanx101.com/blog/math-r/) juga disebabkan oleh proses _review_ materi-materi kuliah sarjana lalu.

Ternyata tidak serumit yang saya bayangkan. _hehehe_.

_Gimana sih soalnya?_

Ini saya berikan beberapa contoh:

1. Matematika:
    - Misalkan diberikan fungsi $f(x)$, kita harus menghitung nilai:
        - $f(a), f'(x), \int f(x)$.
        - Nilai maksimum dan minimum $f(x)$.
    - Diberikan suatu matriks $A$, kita harus menghitung:
        - Nilai eigen.
        - $A^{-1}, A^T$.
        - Menyelesaikan SPL dari $A$.
    - Menghitung solusi persamaan $g(x)$ dengan metode numerik tertentu.
1. Fisika:
    - Menghitung gaya pada suatu sistem tertentu.
    - Mengitung $v$ dan $a$ dari suatu fungsi jarak terhadap waktu $s(t)$.
    
Selain tes tertulis seperti itu, saya juga harus melewati proses wawancara. Ini yang lebih sulit dibandingkan tes tertulis menurut saya. _hehehe_. Sebenarnya cukup dilalui dengan santai saja, kebetulan kemarin saya sempat tidak percaya diri karena sudah lama tidak berada di dunia akademis.

---

Alhamdulillah, Jumat tanggal 11 Juni 2021 lalu saya dinyatakan lulus. InsyaAllah dalam beberapa hari ini saya akan daftar ulang.

Kini tinggal memikirkan bagaimana caranya agar bisa lulus tepat waktu sambil tetap bekerja.

> Iya! Sambil bekerja. Karena hanya magister di SBM ITB saja yang memiliki kelas karyawan. Selainnya adalah kelas reguler. 

Minta _booster_ doanya ya.

Aamiin.