---
title: "Explainable AI: Prediksi Harga Mobil yang Dijual di Situs Carmudi"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/ikanx101 BLOG/_posts/Explainable AI/post 3")

rm(list=ls())
library(dplyr)
library(DALEX)
library(caret)
library(pROC)

load("siap_post.rda")
```

Pada saat menikah dulu, tidak pernah terbersit di kepala saya bahwa memiliki mobil adalah suatu kebutuhan primer hingga anak saya yang sulung lahir. Beberapa kali ada kondisi yang mengharuskan saya harus memiliki mobil sebagai sarana transportasi keluarga. Pada saat itu, uang saya tidak cukup untuk membeli mobil baru secara tunai. Akhirnya saya dan istri mencari-cari mobil bekas di salah satu _dealer_ mobil bekas milik Astra.  

Waktu itu, kami dijodohkan dengan mobil sedan Honda City warna hitam tahun 2003 yang _body_-nya masih _gres_. Kilometernya juga baru 100 ribuan (mengingat sudah 10 tahunan mobil itu berada di jalanan). Akhirnya dengan harga tak sampai 100 juta, kami pinang mobil tersebut.

Jika ditanyakan kepada saya:

> Apakah harga tersebut kemahalan atau tidak?

Saya akan langsung menjawab __tidak tahu__.


---

Saya sendiri tidak terlalu mengerti apa yang menjadi patokan harga mobil bekas.