---
title: "Perbedaan Uji Mean Dua Sampel Independen dan Dependen"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Perbedaan uji _mean_ dua sampel independen dan dependen terletak pada sifat hubungan antara sampel yang diuji. Sampel independen adalah sampel yang tidak memiliki hubungan satu sama lain, sedangkan sampel dependen adalah sampel yang memiliki hubungan satu sama lain. Maksudnya apa?

## Uji _mean_ dua sampel independen

Uji _mean_ dua sampel independen digunakan untuk menguji apakah dua populasi yang berbeda memiliki rata-rata yang sama. Sampel yang diuji independen artinya sampel yang satu tidak dipengaruhi oleh sampel yang lain.

Contohnya:

- Sebuah perusahaan ingin mengetahui apakah ada perbedaan rata-rata tingkat kepuasan pelanggan antara pelanggan yang menggunakan produk A dan pelanggan yang menggunakan produk B.
- Seorang peneliti ingin mengetahui apakah ada perbedaan rata-rata hasil belajar antara siswa yang menggunakan metode pembelajaran A dan siswa yang menggunakan metode pembelajaran B.

## Uji _mean_ dua sampel dependen

Uji _mean_ dua sampel dependen digunakan untuk menguji apakah dua kelompok data dari populasi yang sama memiliki rata-rata yang sama. Sampel yang diuji dependen artinya sampel yang satu berhubungan dengan sampel yang lain. Biasanya digunakan untuk menguji kasus _befor vs after_.

Contohnya:

- Seorang guru ingin mengetahui apakah ada perbedaan rata-rata nilai ujian di suatu kelas sebelum dan sesudah penerapan program bimbingan belajar.
- Seorang peneliti hendak mengetahui kadar kolesterol sekelompok orang sebelum dan setelah mengkonsumsi obat tertentu.

