---
title: "Optimization Story: Menentukan Letak Pool Taxi dengan Mixed Integer Linear Programming"
output:
  github_document:
     pandoc_args: --webtex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(ggplot2)
load("bahan_blog.rda")
```

Beberapa waktu lalu, saya dan beberapa rekan di kantor berdiskusi ringan mengenai data spasial (_longlat location_).

> Apa sih faedahnya jika kita memiliki data spasial?

Ada beberapa hal yang bisa kita lakukan. Salah satunya adalah menentukan rute terbaik dengan algoritma TSP. Tapi ada satu hal yang belum pernah lakukan. Apa itu?

> Sekarang saya akan mengawinkan antara optimisasi _mixed integer linear programming_ dengan analisa spasial.

Optimisasi ini bisa digunakan untuk berbagai macam kasus, tapi kali ini saya akan menggunakan kasus yang umum terjadi saja _yah_. Nanti jika ada kasus berbeda tapi mirip-mirip cara berpikirnya, kita tinggal mengubah formulasi matematikanya saja.

---

# _Problem_

Suatu perusahaan taxi sedang mempertimbangkan untuk membangun beberapa _pool taxi_ untuk mendekatkan mereka kepada konsumen-konsumennya. Mereka memiliki data lokasi-lokasi mana saja memiliki _high demand_ terhadap taxi mereka.

Tercatat ada `r titik` buah lokasi yang memiliki _high demand_. Mereka juga telah melakukan survey terhadap `r toko` buah calon lokasi _pool_ taxi. Masing-masing calon lokasi _pool_ taxi tersebut memiliki harga sewa yang beragam.

