---
title: "Membuat Proposal Market Research"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

_Weekend_ ini saya mendapatkan kesempatan untuk berbagi tentang _market research_ kepada teman-teman mahasiswa melalui forum yang diadakan oleh AIESEC Indonesia.

Salah satu bentuk tugas yang diberikan kepada para peserta adalah mereka harus membuat _market research proposal_ dan kuesioner sederhana dari satu kasus _marketing_.

Untuk membuat kuesioner, saya sudah pernah membahas panduan singkatnya di [sini](https://ikanx101.com/blog/kuesioner-mr/).

---

> ___Apa sih kegunaan dari market research proposal?___

Sesuai dengan namanya, _proposal_ berarti perencanaan. 

> ___Gagal dalam merencanakan berarti merencanakan kegagalan.___

Salah satu kegunaan _proposal_ yang menurut saya paling penting adalah sebagai _guidelines_ bagi _researchers_ dan _client_ dalam melaksanakan _market research_.

Apa saja isi proposalnya? Setidaknya ada beberapa bagian berikut ini:

1. Latar belakang masalah.
    - Mungkin bagian ini terkesan formalitas saja tapi menurut saya justru ini adalah bagian yang terpenting. Seorang _researcher_ yang baik harus bisa menemukan dan menuliskan masalah yang dihadapinya dengan jelas dan runut.
    - Masih ingat dengan pembahasan saya di [tulisan ini](https://ikanx101.com/blog/tujuan/)?
    - _Market research_ harus bisa menyelesaikan permasalahan yang ada. Oleh karena itu, titik kritis pertama yang harus diselesaikan dengan baik adalah memformulasikan masalah.
1. Tujuan riset.
    - Dari masalah di atas, kita harus menurunkannya menjadi tujuan riset. Kelak kuesioner atau pertanyaan-pertanyaan yang ada harus bisa menjawab tujuan dari riset ini.
1. Metode penelitian.
    - Metode penelitian adalah bagian yang paling seru. 
    - Pada bagian ini, kita harus menentukan metode apa yang hendak kita pakai. 
        - Apakah kualitatif? 
        - Ataukah kuantitatif? 
    - Sumber data apa yang hendak kita akan gunakan?
        - Apakah data primer?
        - Apakah data sekunder?
    - Siapa target responden kita? Apa saja kriteria responden tersebut?
    - Berapa banyak responden yang dibutuhkan?
    - Mana saja _coverage_ atau area riset?
1. Dasar teori.
    - Pada bagian ini, kita sebaiknya menjelaskan dasar teori dan rencana analisa yang hendak dilakukan dengan data hasil riset tersebut.
    - Biasanya saya menambahkan:
        - Data sekunder yang bisa menunjang masalah riset. Data sekunder ini bisa berasal dari _previous research_ atau data publik lainnya yang terkait.
        - Teori-teori yang berkaitan dengan riset. Contoh seerhana adalah jika kita hendak melakukan suatu pengukuran tertentu, kita bisa memberikan penjelasan terkait definisi dan cara pengukuran tersebut.
        - _Mock up_ analisa yang hendak dilakukan.
1. _Timeline_.
    - _Timeline_ pelaksanaan riset juga biasa merupakan bagian yang diremehkan padahal ini adalah bagian yang penting juga.
    - Kita harus bisa menjaga agar pelaksanaan riset dilakukan tepat waktu sehingga momen tetap terjaga.
1. _Budget_.
    - Bagian ini biasanya wajib ada pada proposal profesional.
1. _Research team_
    - Bagian ini biasanya wajib ada pada proposal profesional.
    - Di bagian ini perlu dijelaskan siapa saja tenaga ahli yang turut serta dalam _project market research_ tersebut.
    
Agar lebih jelas, teman-teman bisa membaca _links_ yang saya sertakan di atas yah.

---

`if you find this article helpful, support this blog by clicking the ads.`