---
title: "Mengenal Brand Map / Perceptual Map dalam Market Research"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls())
setwd("~/ikanx101.github.io/_posts/matematika ITB/brand map")

rm(list=ls())

library(dplyr)
library(tidyr)

df = mtcars |> mutate(merek = row.names(mtcars)) |> 
     select(merek,mpg,disp,hp,wt,qsec) |>
     separate(merek,
              into = c("merek","dummy"),
              sep  = " ") |>
     group_by(merek) |>
     summarise_all(mean) |>
     ungroup() |>
     select(-dummy) |>
     as.data.frame()

```


```{r}
row.names(df) = df$merek
df$merek      = NULL
df
```

```{r}
library(factoextra)

res.pca <- prcomp(df, scale = TRUE)
fviz_eig(res.pca)
```


```{r}
fviz_pca_ind(res.pca,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )

fviz_pca_var(res.pca,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
```


```{r}
fviz_pca_biplot(res.pca, repel = TRUE,
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969"  # Individuals color
                )
```






