{
  "hash": "ce2ae7f7c1bca143f906ee1070e63ced",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Pengaruh Cuaca terhadap Market Otomotif di Indonesia (Baca Sampai Selesai)\"\nformat: \n  gfm:\n    html-math-method: webtex\n    fig-dpi: 500\n    fig-width: 8\n    fig-height: 4.5\n    fig-align: center\neditor: visual\nexecute:\n  echo: false\n  warning: false\n  error: false\n---\n\n::: {.cell}\n\n:::\n\n\n\nDi siang hari yang panas, saya tetiba berpikir:\n\n> Kalau suasana panas seperti ini, paling enak kalau bepergian naik mobil dibandingkan motor. _Bisa pakai AC, lebih adem_. __Begitu pikir saya__.\n\nSetelah dipikirkan kembali, jangan-jangan cuaca bisa mempengaruhi banyaknya unit mobil yang terjual. Jika begitu, saya bisa membuat model _machine learning_ sederhana untuk membuktikan dugaan tersebut.\n\nLangsung saja saya mencari __artikel terpercaya__ yang bisa saya gunakan sebagai basis logikanya. Caranya adalah dengan bertanya ke __Gemini Bard Google__. Begini katanya:\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Screenshot from 2024-05-30 08-41-45.png){width=60%}\n:::\n:::\n\n\n\nLalu segera saya cari data utama seperti:\n\n1. Rata-rata suhu tahunan di Indonesia.\n1. Total unit mobil terjual di Indonesia.\n\nBerikut adalah data suhu yang saya dapatkan dari berbagai macam sumber:\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| Tahun | Suhu Rata-rata Tahunan (°C) |\n|:-----:|:---------------------------:|\n| 2015  |            26.6             |\n| 2016  |            26.9             |\n| 2017  |            26.8             |\n| 2018  |            26.8             |\n| 2019  |            26.9             |\n| 2020  |            27.0             |\n| 2021  |            27.0             |\n| 2022  |            27.0             |\n\n\n:::\n:::\n\n\n\nBerikut adalah data unit mobil terjual yang saya dapatkan dari berbagai macam sumber:\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| Tahun | Unit Mobil Terjual |\n|:-----:|:------------------:|\n| 2015  |      1028000       |\n| 2016  |      1009000       |\n| 2017  |      1079000       |\n| 2018  |      1151000       |\n| 2019  |      1030000       |\n| 2020  |       532407       |\n| 2021  |       887200       |\n| 2022  |       915159       |\n\n\n:::\n:::\n\n\n\nPertama-tama, saya akan buat _scatterplot_ berikut ini:\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](korelasi_files/figure-commonmark/unnamed-chunk-5-1.png)\n:::\n:::\n\n\n\nJika dilihat sekilas, sepertinya saya bisa membuat model _machine learning_ yang punya akurasi bagus. Untuk itu, saya akan membuat model regresi polinomial.\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sales ~ poly(suhu, 4, raw = TRUE), data = df_model)\n\nResiduals:\n         1          2          3          4          5          6          7 \n-4.080e-08 -1.050e+04 -3.600e+04  3.600e+04  1.050e+04 -2.458e+05  1.089e+05 \n         8 \n 1.369e+05 \n\nCoefficients: (1 not defined because of singularities)\n                             Estimate Std. Error t value Pr(>|t|)\n(Intercept)                 9.190e+10  6.776e+11   0.136    0.899\npoly(suhu, 4, raw = TRUE)1 -9.238e+09  6.740e+10  -0.137    0.898\npoly(suhu, 4, raw = TRUE)2  2.612e+08  1.885e+09   0.139    0.897\npoly(suhu, 4, raw = TRUE)3         NA         NA      NA       NA\npoly(suhu, 4, raw = TRUE)4 -6.183e+04  4.371e+05  -0.141    0.894\n\nResidual standard error: 153200 on 4 degrees of freedom\nMultiple R-squared:  0.6281,\tAdjusted R-squared:  0.3492 \nF-statistic: 2.252 on 3 and 4 DF,  p-value: 0.2245\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"R square: \"\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6281415\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"MAPE: \"\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1024251\n```\n\n\n:::\n:::\n\n\n\nModel polinomial orde 4 menghasilkan $R^2 = 0.6281415$ dengan $MAPE = 0.1024251$. \n\nSaya buat grafik untuk mengecek _fitted values_ dengan data _real_ dari _scatterplot_ sebelumnya:\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](korelasi_files/figure-commonmark/unnamed-chunk-7-1.png)\n:::\n:::\n\n\n\nSaya cukup puas dengan performa model _machine learning_ yang dibuat tersebut. \n\n> ___Ternyata semakin panas suhu yang terjadi di Indonesia, semakin menurun unit mobil terjual.___\n\n## _Epilog_\n\nCerita di atas adalah __cerita rekaan atau karangan__ saja _yah_. Saya terinspirasi dari kisah nyata yang saya dengar belum lama ini. \n\nDari proses berpikir, pencarian artikel, pengumpulan data, hingga pembuatan model dan pengambilan kesimpulan menurut saya ada beberapa _flaws_ yang berujung fatal. Apa saja? Mari kita bahas satu per satu:\n\n1. Kita sebenarnya tidak bisa menghubungkan kausalitas antara __cuaca__ dan ___sales___ mobil secara langsung. Kenapa? Secara logika, terlalu banyak _middle factors_ bagi konsumen untuk membeli mobil.\n1.Jangan pernah bertanya seperti ini pada _Gemini_, _ChatGPT_, _Bing_, dan sejenisnya. Kenapa? Kalian hanya akan mendapatkan artikel _very optimist_ yang sejatinya belum jelas kebenarannya. Maksudnya, kalian akan mendapatkan artikel-artikel yang bernada _Yes Man!_ di mana semua hal yang kita tanyakan bisa dilakukan dan dibuat.\n1. Perhatikan banyaknya baris data saat membuat model _machine learning_! Jangan membuat model dengan baris data yang sedikit dan terbatas!\n1. Jangan tergiur untuk membuat model yang memiliki akurasi dan presisi yang __sempurna__! Lebih baik kita membuat model yang bisa dengan mudah diinterpretasikan.\n\nSelain poin-poin di atas, apa lagi _flaws_ yang bisa kalian dapatkan dari cerita di atas?",
    "supporting": [
      "korelasi_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}