---
title: "Refleksi Karir: Langkanya Ucapan Terima Kasih"
format: 
  gfm:
    html-math-method: webtex
    toc: false
    toc-depth: 4
    fig-dpi: 500
    fig-width: 8
    fig-height: 4.5
editor: visual
execute:
  echo: false
  warning: false
  error: false
---

Beberapa hari yang lalu, saya tak sengaja mengobrol dengan salah seorang kolega tentang perjalanan karir di dunia _market research_. Kalau dipikirkan lebih lanjut, saya jadi merasa ada beberapa kisah yang menarik untuk diceritakan. Oleh karena itu, saya akan buat satu topik bahasan baru di blog saya ini untuk menceritakan pengalaman tersebut.

---

Pada tulisan pertama ini, saya akan bercerita mengenai salah satu pengalaman saya bekerja di perusahaan pertama yakni sebuah _market research agency_ terkenal di bidang perbankan di Jakarta Selatan pada 2008 silam.

Alkisah, setelah saya lulus _probation_ sebagai _market research executive_ di perusahaan tersebut, saya mulai dipercaya untuk memegang satu _project_ secara penuh. Walaupun tetap didampingi oleh seorang _supervisor_ (atasan saya) tapi saya memegang kendali di belakang kemudi _project_ tersebut. _Project_-nya adalah melakukan _mistery shopping_ layanan perbankan untuk salah satu bank BUMN terbesar di Indonesia.

Salah satu tantangan terbesar yang harus saya hadapi saat itu adalah me-_manage_ suatu _project_ skala nasional. Pada saat itu, _fieldwork_ berjalan tidak hanya di kota-kota besar di Indonesia tapi sampai ke kota pelosok (maklum saat itu bank tersebut identik dengan bank pedesaan. Kalian tahu kan ya? Hehe).

Saya yang kuliahnya di MIPA dan tidak terlalu banyak berhubungan dengan banyak orang harus belajar keluar dari _boundaries_. Perlahan saya mencoba menjadi _people person_ agar bisa diterima oleh bagian lain dalam perusahaan tersebut. Oh iya, sebagai _market research executive_ saya berhubungan erat dengan tiga bagian lain, yaitu:

1. _Field_: sebagai ujung tombak pengumpul data.
1. _Data processing_: sebagai mitra utama dalam melakukan analisa dan membuat _report_.
1. _Finance_: sebagai tempat meminta _budget_ ini dan itu. _hehe_.

Tipikal orang-orang dari ketiga bagian tersebut juga berbeda-beda. Oleh karena itu pendekatan yang saya lakukan juga berbeda-beda tentunya. Namun ada satu metode yang _general_, yakni: __empati__. Sayang sekali __empati__ ini saya rasa tidak terpupuk denga baik pada perusahaan pertama saya tersebut __saat itu__ (semoga saat ini sudah membaik - Aamiin).

Salah satu contohnya adalah __pelarangan setiap__ ___market research executive___ __untuk menolong__ ___market research executive___ __yang lain__. Itu baru contoh intra bagian. Apalagi kalau beda bagian kan? Hehe.

Singkat cerita, setelah empat bulan, _project_ sudah selesai dijalankan. Presentasi sudah dilakukan, klien puas dan ada _repeat order_ untuk _project_ berikutnya dengan skala yang semakin masif.

Saya pribadi merasa kesuksesan _project_ itu adalah kesuksesan tim dan perusahaan secara menyeluruh. Tidak ada __pahlawan tunggal__ yang patut diberikan pujian. Oleh karena itu di akhir _project_, saya coba merangkai satu _email_ yang ditujukan ke semua bagian terkait.

Inti dari _email_ itu adalah ucapan terima kasih sudah mendukung dan mensukseskan _project_ ini. Saya sampaikan juga harapan agar kita bisa kembali menjalankan _next project_ dengan kompak. Sebuah _email_ sederhana tapi saya rasa penting untuk saya sampaikan. _Email_ saya kirimkan setelah jam makan siang.

Sore harinya saat hendak pulang, saya melewati _workcenter_ tim _field_