---
title: "Rute Jalan-Jalan di Jogjakarta"
author: '@mr.ikanx'
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(leaflet)
library(dplyr)
library(TSP)
```

```{r}
df = data.frame(
  tempat = c("Patra Malioboro",
             "Eastparc Hotel",
             "The Westlake Resort",
             "Rumah",
             "HeHa Ocean View",
             "Jejamuran",
             "Bakmi Mbah Gito",
             "Merapi Park Jogjakarta",
             "Pengilon",
             "Warung Pesona Sabin",
             "Warung Kulinan",
             "Pawon Mbah Gito"),
  lat = c(-7.7917252,
          -7.7815183,
          -7.7474907,
          -6.2845666,
          -8.1060611,
          -7.7053761,
          -7.8133577,
          -7.620913,
          -7.7290051,
          -7.789498,
          -7.7272225,
          -7.7089696
          ),
  lng = c(110.3615326,
          110.4045034,
          110.3353893,
          106.6994883,
          110.4593214,
          110.3589751,
          110.3929303,
          110.4195791,
          110.3755005,
          110.3417494,
          110.3819675,
          110.4109756
          )
)

df

df_tsp = df %>% select(-tempat)
matriks = dist(df_tsp,upper = T) %>% as.matrix()

# antar hotel harus jauh
matriks[1,2] = 999
matriks[2,1] = 999
matriks[1,3] = 999
matriks[3,1] = 999
matriks[2,3] = 999
matriks[3,2] = 999

# rumah ke patra harus dekat
matriks[4,1] = 0
matriks[1,4] = 0
matriks[2,4] = 0
matriks[4,2] = 0

matriks

problem = as.ATSP(matriks)
hasil = solve_TSP(problem)
hasil
paste(df$tempat[as.integer(hasil)],collapse = " - ")
```



```{r}
final = df[as.integer(hasil),]

final 

m = 
  leaflet() %>% 
  addTiles() %>% 
  addCircles(data = final,
             lng = ~lng,
             lat = ~lat,
             color = "darkred",
             radius = 10,
             popup = ~tempat) %>% 
  addPopups(data = final,
            lng = ~lng,
            lat = ~lat,
            final$tempat,
    options = popupOptions(closeButton = FALSE)
  )

mydf = final %>% rename(InitialLat = lat,
                        InitialLong = lng)
mydf$NewLat = c(mydf$InitialLat[2:nrow(mydf)],
                mydf$InitialLat[1])

mydf$NewLong = c(mydf$InitialLong[2:nrow(mydf)],
                 mydf$InitialLong[1])


for (i in 1:nrow(mydf)){
  m = m %>%
    addPolylines(lat=c(mydf[i,]$InitialLat,
                       mydf[i,]$NewLat),
                 lng=c(mydf[i,]$InitialLong,
                       mydf[i,]$NewLong))
} 

m
```