---
title: "Membandingkan Multiple Regression Models dengan `mtable()`"
format:
  gfm:
    html-math-method: webtex
    fig-dpi: 500
    fig-width: 8
    fig-height: 4.5
    editor: visual
execute:
  warning: false
  error: false
---

Pada tahun ini, saya sudah mengerjakan beberapa _projects_ terkait model regresi (baik linear atau tak linear). Biasanya saya agak kesulitan dalam membuat visualisasi perbandingan dua atau lebih model regresi. 

Padahal informasi yang hendak saya tampilkan cukup simpel, yakni:

1. Seberapa bagus model tersebut. Biasanya saya cukup menampilkan nilai $R^2$.
1. Variabel mana saja yang __signifikan__ terhadap model.

Jika biasanya saya harus membuat _function_ mandiri untuk menampilkan informasi tersebut, ternyata saya bisa menggunakan _function_ `mtable()` dari `library(memisc)` di __R__.

Sebagai contoh, saya akan menggunakan data `mtcars` sebagai berikut:

```{r}
# Menghapus semua objek dari lingkungan kerja (workspace) R
rm(list=ls()) 

# Membuat model regresi linear (model1) dengan mpg sebagai variabel dependen dan disp, carb, hp, dan cyl sebagai variabel independen, menggunakan dataset mtcars
model1 = lm(mpg ~ disp + carb + hp + cyl, data = mtcars) 

# Membuat model regresi linear (model2) dengan mpg sebagai variabel dependen dan disp dan carb sebagai variabel independen, menggunakan dataset mtcars
model2 = lm(mpg ~ disp + carb, data = mtcars) 

# Membuat model regresi linear (model3) dengan mpg sebagai variabel dependen dan hp dan cyl sebagai variabel independen, menggunakan dataset mtcars
model3 = lm(mpg ~ hp + cyl, data = mtcars) 

# Memuat package 'memisc' yang menyediakan fungsi untuk manajemen data dan hasil model statistik
library(memisc) 
mtable("Model 1" = model1, 
       "Model 2" = model2,
       "Model 3" = model3) 
```

Tabel di atas sudah memuat cukup informasi-informasi yang penting bagi saya.

---

`if you find this article helpful, support this blog by clicking the ads.`

