---
title: "Mencoba LLM Huggingface: Tanya Jawab Menggunakan AI"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# url
# https://huggingface.co/Rifky/Indobert-QA
```

Tulisan ini adalah tulisan ketiga dari [oprekan saya terkait model-model LLM dari situs _Huggingface_](https://ikanx101.com/tags/#huggingface). Buat rekan-rekan yang sudah terbiasa menggunakan `ChatGPT` dan `Google Bard`, pasti sudah sering menggunakan __AI__ _tools_ tersebut untuk menanyakan berbagai macam hal.

> Salah satu fitur yang biasanya sering digunakan adalah membuat __AI__ _tools_ "mengerti" suatu dokumen teks, lalu kita bisa menanyakan berbagai macam hal terkait dokumen tersebut. 

Saat saya berkeliling di situs [_Huggingface_](https://huggingface.co/), saya menemukan [satu model LLM bernama `Indobert-QA`](https://huggingface.co/Rifky/Indobert-QA) buatan __maestro lokal__ yang memiliki fitur serupa. Berikut adalah sitasi dari _paper_ penelitiannya:

```
Fajri Koto and Afshin Rahimi and Jey Han Lau and Timothy Baldwin. 
2020. 
IndoLEM and IndoBERT: A Benchmark Dataset and Pre-trained Language Model for Indonesian NLP. 
Proceedings of the 28th COLING.
```

---

## Pengujian

Untuk menguji model tersebut, saya akan memberikan satu teks karangan berikut ini:

> _Bergulingnya pemerintahan Presiden Soeharto lantas membuat pemilu dipercepat dan dilaksanakan pada tahun 1999. Padahal, seharusnya pemilu baru diadakan lagi pada tahun 2002. Dengan persiapan yang tergolong singkat, pemilu 1999 diselenggarakan pada 7 Juni 1999. Pemilu pada tahun itu terlaksana secara damai tanpa ada kekacauan. Cara pembagian kursi hasil pemilihan ini menggunakan sistem proporsional. Namun, penetapan calon terpilih berbeda dengan pemilu sebelumnya, yaitu dengan menentukan peringkat perolehan suara suatu partai di Dapil. Para calon terpilih ditetapkan berdasarkan suara terbesar atau terbanyak dari daerah tempat seseorang dicalonkan. Kemudian dari hasil Sidang Umum MPR, Abdurrahman Wahid (Gus Dur) dan Ketua Umum PDI-P Megawati Soekarnoputri dilantik menjadi Presiden dan Wakil Presiden. Pasangan Abdurrahman Wahid - Megawati Soekarnoputri kemudian digantikan oleh pasangan Megawati Soekarnoputri - Hamzah Haz dari Sidang Istimewa MPR RI, 23 Juli 2001._

Kemudian saya akan menanyakan beberapa hal berikut ini:

---

### Pertanyaan I

__Kapan pemilu dilaksanakan?__

```
{
  "score": 0.3394789695739746,
  "start": 248,
  "end": 259,
  "answer": "7 Juni 1999"
}
```

### Pertanyaan II

__Siapa presiden hasil pemilu 1999?__

```
{
  "score": 0.2801145911216736,
  "start": 692,
  "end": 763,
  "answer": "Abdurrahman Wahid (Gus Dur) dan Ketua Umum PDI-P Megawati Soekarnoputri"
}
```

### Pertanyaan III

__Bagaimana cara pembagian kursi?__

```
{
  "score": 0.5875973105430603,
  "start": 381,
  "end": 400,
  "answer": "sistem proporsional"
}
```

### Pertanyaan IV

__Siapa pendamping Megawati?__

```
{
  "score": 0.9582338333129883,
  "start": 921,
  "end": 931,
  "answer": "Hamzah Haz"
}
```

### Pertanyaan V

__Siapa nama asli Gus Dur?__

```
{
  "score": 0.7926519513130188,
  "start": 692,
  "end": 709,
  "answer": "Abdurrahman Wahid"
}
```

### Pertanyaan VI

__Kapan dilaksanakan sidang istimewa MPR?__

```
{
  "score": 0.867054283618927,
  "start": 961,
  "end": 973,
  "answer": "23 Juli 2001"
}
```

### Pertanyaan VII

__Kapan seharusnya pemilu dilaksanakan?__

```
{
  "score": 0.7955065369606018,
  "start": 168,
  "end": 172,
  "answer": "2002"
}
```

---

## Kesimpulan

Dari hasil __QnA__ tersebut, saya merasa performa modelnya sangat baik ya. Bagaimana menurut Anda?

---

`if you find this article helpful, support this blog by clicking the ads.`