---
title: "Pengalaman Perpanjang SIM di Polres Kota Bekasi pada Era Pandemi"
output: github_document
---

```{r}
rm(list=ls())
```

Kali ini saya mau menulis sesuatu yang diluar kebiasaan _blog_ ini _yah_. Semoga bermanfaat untuk kalian semua.

---

Ceritanya pada bulan Desember 2021 ini, SIM C saya sudah habis masa berlakunya. Sempat terpikir untuk membuat SIM secara _online_ melalui __layanan SIM online Korlantas__. Tapi setelah mendapatkan saran dan rekomendasi dari beberapa teman yang sudah mencoba, akhirnya saya memutuskan untuk tetap memperpanjang SIM secara _offline_ saja.

Beberapa tahun lalu (sebelum ada pandemi), saat SIM A saya habis masa berlakunya, Polres Kota Bekasi menerapkan layanan perpanjangan SIM 24 jam. Dulu saya pernah memperpanjang SIM A pada pukul 04.30 pagi selepas shalat Shubuh.

Nah, saat kondisi pandemi ini saya belum tahu bagaimana mekanisme terbarunya.

_Alhamdulillah_, saat mendengarkan radio Dakta, saya mendapatkan informasi bahwa kini perpanjangan SIM di kota Bekasi bisa dilakukan di:

1. Mall Pelayanan Publik (untuk pagi hari), dan
1. Polres Metro Bekasi (untuk sore hingga malam hari).

Kedua tempat tersebut memiliki kesamaan:

> __Setiap orang yang hendak memperpanjang SIM wajib mendaftar secara online terlebih dahulu.__

Berdasarkan informasi tersebut, saya mencoba untuk mendaftar antrian di Mall Pelayanan Publik melalui situs [__mpp.bekasikota.go.is__](http://mpp.bekasikota.go.id)
